### ISSUE TITLE
Refactor: Should be based on views, not classes.

### ISSUE THREAD

**Issue by dantleech** [psiphp/grid#40]
When constructing a list from a class, you do not have control of the query, nor can you hydrate fields that are not properties of the class.

It would be interesting to see what solutions could be produced by using a query-based approach:

```
psi_grid:
    views:
        customer:
            select: "name, telephone, foobar" # column or field names depending on impl.
            from: "customer" # or Acme\Entity\Customer
            where: "x=y"
    grids:
        customer:
            view: customer
            columns:
                name:
                    type: string
                telephone:
                    type: string
                foobar:
                    type: datetime
                    options:
                        format: Y-m-d
```

This has advantages over the current approach:

- No more confusion about where the data comes from: The column types are restricted to formatting the data.
- Ability to join tables and virtual fields.

And some disadvantages:

- ??
